<?xml version="1.0" encoding="utf-8" ?>
<Project>
    <Target Name="CopyToPlugins" AfterTargets="Build" Condition="'$(CI)' != 'TRUE'">
        <ItemGroup>
            <FilesToCopy Include="$(TargetPath)" />
            <FilesToCopy Include="$(TargetDir)$(TargetName).pdb" Condition="Exists('$(TargetDir)$(TargetName).pdb')" />
            <TupPresetFiles Include="$(MSBuildProjectDirectory)\TUPshaders\Presets\**\*" />
        </ItemGroup>

        <Copy SourceFiles="@(FilesToCopy)" DestinationFiles="@(FilesToCopy->'$(PluginsPath)\$(ProjectName)\%(Filename)%(Extension)')" />
        <MakeDir Directories="$(PluginsPath)\$(ProjectName)\TUPshaders\Presets" />
        <Copy SourceFiles="@(TupPresetFiles)" DestinationFolder="$(PluginsPath)\$(ProjectName)\TUPshaders\Presets\%(RecursiveDir)" SkipUnchangedFiles="true" Condition="'@(TupPresetFiles)' != ''" />
        <Message Text="Copied $(TargetFileName), TUPshaders presets, and PDB to Plugins" Importance="high"/>
    </Target>
</Project>
